carbonrelay:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2003:2003"
   - "2004:2004"
  volumes:
   - ./carbon/relay:/etc/carbon
  links:
   - carboncache1
   - carboncache2

carboncache1:
  image: nuancemobility/carbon
  command: cache
  volumes:
   - ./carbon/cache:/etc/carbon
  volumes_from:
   - heramonitoring_whisper_1

carboncache2:
  image: nuancemobility/carbon
  command: cache
  volumes:
   - ./carbon/cache:/etc/carbon
  volumes_from:
   - heramonitoring_whisper_1

graphite:
  image: nuancemobility/graphite-web
  volumes:
   - ./graphite-web:/etc/graphite
  volumes_from:
   - heramonitoring_whisper_1
  links:
   - carboncache1
   - carboncache2

elasticsearch:
  image: elasticsearch:1.6
  command: -Des.node.name="hera_elasticsearch_001" -Des.bootstrap.mlockall=true
  environment:
   - ES_HEAP_SIZE=2g
  volumes_from:
   - heramonitoring_elasticsearchdata_1

elasticsearchcurator:
  image: nuancemobility/elasticsearch-curator
  links:
   - elasticsearch
  volumes:
   - ./elasticsearch-curator:/config

grafana:
  image: nuancemobility/grafana
  volumes:
   - ./grafana/config.js:/usr/share/grafana/config.js

kibana3:
  image: nuancemobility/kibana
  volumes:
   - ./kibana:/config

kibana4:
  image: kibana:4.1
  links:
   - elasticsearch

logstash:
  image: logstash:1.5
  command: -f /config-dir/
  environment:
   - LS_HEAP_SIZE=2048m
  links:
   - elasticsearch
  volumes:
   - ./logstash/config:/config-dir
   - ./mib:/mib
   - ./logstash/ssl:/etc/pki/tls
  ports:
   - "5000:5000/udp"
   - "5001:5001"

sensu:
  image: nuancemobility/sensu
  links:
   - carbonrelay
   - rabbitmq
  volumes:
   - ./sensu/config:/etc/sensu/conf.d
   - ./sensu/handlers:/etc/sensu/handlers

uchiwa:
  image: uchiwa/uchiwa
  links:
   - sensu
  volumes:
   - ./uchiwa:/config
  ports:
   - "3030:3000"

sensuclient:
  image: nuancemobility/sensu-client
  volumes:
   - ./sensu-client/config:/etc/sensu/conf.d
   - ./sensu-client/plugins:/etc/sensu/plugins
   - ./mib:/etc/sensu/mib
   - /var/run:/var/run:rw
   - /sys:/sys:ro
#   - /proc:/proc:ro
  net: host
  privileged: true

cadvisor:
  image: google/cadvisor:0.15.1
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro

monitoringproxy:
  image: nuancemobility/nginx
  links:
   - uchiwa
   - grafana
   - kibana3
   - kibana4
   - elasticsearch
   - cadvisor
   - graphite
   - configsynchronizer
   - screenshoter
  volumes:
   - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
   - ./nginx/config/includes:/etc/nginx/includes
   - ./nginx/html:/usr/share/nginx/html
   - ./nginx/ssl:/etc/nginx/ssl
  ports:
   - "443:443"
   - "8080:8080"
   - "4242:4242"

configsynchronizer:
  image: nuancemobility/hera-config-synchronizer
  links:
   - elasticsearch
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200/
   - GIT_REPOSITORY=https://github.com/Nuance-Mobility/hera-dashboards-example.git

screenshoter:
  image: nuancemobility/web-screenshoter

rabbitmq:
  image: rabbitmq:3.5
  ports:
   - "5672:5672"
